name: Scan

on:
  push:
    branches:
      - '**/**'

jobs:
  test:
    name: 'Test and Lint'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Test
      run: yarn test
    - name: Lint
      run: yarn lint

  trigger-deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'
    steps:
      - name: Set environment
        id: setvars
        run: |
          if [[ "${{ github.base_ref }}" == "dev" || "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "environment=dev" >> $GITHUB_OUTPUT
          fi
          if [[ "${{ github.base_ref }}" == "main" || "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "environment=prod" >> $GITHUB_OUTPUT
          fi
      - name: Trigger deploy
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/${{ github.repository }}/actions/workflows/deploy.yml/dispatches
          ref: ${{ github.ref }}
          inputs:
            environment: ${{ steps.setvars.outputs.environment }}
