name: Scan

on:
  push:
      branches:
        - '**/**'

jobs:
  test:
    name: 'Test and Lint'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Test
      run: yarn test
    - name: Lint
      run: yarn lint
  
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v3
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Release
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
